// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: spire/api/server/bootstrap/v1/bootstrap.proto

package bootstrapv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTrustAnchorARNRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTrustAnchorARNRequest) Reset() {
	*x = GetTrustAnchorARNRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spire_api_server_bootstrap_v1_bootstrap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTrustAnchorARNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrustAnchorARNRequest) ProtoMessage() {}

func (x *GetTrustAnchorARNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_server_bootstrap_v1_bootstrap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrustAnchorARNRequest.ProtoReflect.Descriptor instead.
func (*GetTrustAnchorARNRequest) Descriptor() ([]byte, []int) {
	return file_spire_api_server_bootstrap_v1_bootstrap_proto_rawDescGZIP(), []int{0}
}

type GetTrustAnchorARNResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ARN of the trust anchor created by the SPIRE server
	TrustAnchorArn string `protobuf:"bytes,1,opt,name=trust_anchor_arn,json=trustAnchorArn,proto3" json:"trust_anchor_arn,omitempty"`
}

func (x *GetTrustAnchorARNResponse) Reset() {
	*x = GetTrustAnchorARNResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spire_api_server_bootstrap_v1_bootstrap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTrustAnchorARNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrustAnchorARNResponse) ProtoMessage() {}

func (x *GetTrustAnchorARNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_server_bootstrap_v1_bootstrap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrustAnchorARNResponse.ProtoReflect.Descriptor instead.
func (*GetTrustAnchorARNResponse) Descriptor() ([]byte, []int) {
	return file_spire_api_server_bootstrap_v1_bootstrap_proto_rawDescGZIP(), []int{1}
}

func (x *GetTrustAnchorARNResponse) GetTrustAnchorArn() string {
	if x != nil {
		return x.TrustAnchorArn
	}
	return ""
}

var File_spire_api_server_bootstrap_v1_bootstrap_proto protoreflect.FileDescriptor

var file_spire_api_server_bootstrap_v1_bootstrap_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2f, 0x76, 0x31, 0x2f,
	0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1d, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x22, 0x1a,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x54, 0x72, 0x75, 0x73, 0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72,
	0x41, 0x52, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x45, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x54, 0x72, 0x75, 0x73, 0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x41, 0x52, 0x4e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x74, 0x72, 0x75, 0x73, 0x74,
	0x5f, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x5f, 0x61, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x41, 0x72,
	0x6e, 0x32, 0x94, 0x01, 0x0a, 0x09, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x12,
	0x86, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x54, 0x72, 0x75, 0x73, 0x74, 0x41, 0x6e, 0x63, 0x68,
	0x6f, 0x72, 0x41, 0x52, 0x4e, 0x12, 0x37, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72,
	0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x75, 0x73, 0x74, 0x41, 0x6e,
	0x63, 0x68, 0x6f, 0x72, 0x41, 0x52, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x38,
	0x2e, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x72, 0x75, 0x73, 0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x41, 0x52, 0x4e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x51, 0x5a, 0x4f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x70, 0x69, 0x66, 0x66, 0x65, 0x2f, 0x73, 0x70,
	0x69, 0x72, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2f, 0x76, 0x31, 0x3b,
	0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_spire_api_server_bootstrap_v1_bootstrap_proto_rawDescOnce sync.Once
	file_spire_api_server_bootstrap_v1_bootstrap_proto_rawDescData = file_spire_api_server_bootstrap_v1_bootstrap_proto_rawDesc
)

func file_spire_api_server_bootstrap_v1_bootstrap_proto_rawDescGZIP() []byte {
	file_spire_api_server_bootstrap_v1_bootstrap_proto_rawDescOnce.Do(func() {
		file_spire_api_server_bootstrap_v1_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(file_spire_api_server_bootstrap_v1_bootstrap_proto_rawDescData)
	})
	return file_spire_api_server_bootstrap_v1_bootstrap_proto_rawDescData
}

var file_spire_api_server_bootstrap_v1_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_spire_api_server_bootstrap_v1_bootstrap_proto_goTypes = []interface{}{
	(*GetTrustAnchorARNRequest)(nil),  // 0: spire.api.server.bootstrap.v1.GetTrustAnchorARNRequest
	(*GetTrustAnchorARNResponse)(nil), // 1: spire.api.server.bootstrap.v1.GetTrustAnchorARNResponse
}
var file_spire_api_server_bootstrap_v1_bootstrap_proto_depIdxs = []int32{
	0, // 0: spire.api.server.bootstrap.v1.Bootstrap.GetTrustAnchorARN:input_type -> spire.api.server.bootstrap.v1.GetTrustAnchorARNRequest
	1, // 1: spire.api.server.bootstrap.v1.Bootstrap.GetTrustAnchorARN:output_type -> spire.api.server.bootstrap.v1.GetTrustAnchorARNResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spire_api_server_bootstrap_v1_bootstrap_proto_init() }
func file_spire_api_server_bootstrap_v1_bootstrap_proto_init() {
	if File_spire_api_server_bootstrap_v1_bootstrap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spire_api_server_bootstrap_v1_bootstrap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTrustAnchorARNRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spire_api_server_bootstrap_v1_bootstrap_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTrustAnchorARNResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spire_api_server_bootstrap_v1_bootstrap_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spire_api_server_bootstrap_v1_bootstrap_proto_goTypes,
		DependencyIndexes: file_spire_api_server_bootstrap_v1_bootstrap_proto_depIdxs,
		MessageInfos:      file_spire_api_server_bootstrap_v1_bootstrap_proto_msgTypes,
	}.Build()
	File_spire_api_server_bootstrap_v1_bootstrap_proto = out.File
	file_spire_api_server_bootstrap_v1_bootstrap_proto_rawDesc = nil
	file_spire_api_server_bootstrap_v1_bootstrap_proto_goTypes = nil
	file_spire_api_server_bootstrap_v1_bootstrap_proto_depIdxs = nil
}
