// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package bootstrapv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// BoostrapClient is the client API for Boostrap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BoostrapClient interface {
	// Get trust anchor ARN
	GetTrustAnchorARN(ctx context.Context, in *GetTrustAnchorARNRequest, opts ...grpc.CallOption) (*GetTrustAnchorARNResponse, error)
}

type boostrapClient struct {
	cc grpc.ClientConnInterface
}

func NewBoostrapClient(cc grpc.ClientConnInterface) BoostrapClient {
	return &boostrapClient{cc}
}

func (c *boostrapClient) GetTrustAnchorARN(ctx context.Context, in *GetTrustAnchorARNRequest, opts ...grpc.CallOption) (*GetTrustAnchorARNResponse, error) {
	out := new(GetTrustAnchorARNResponse)
	err := c.cc.Invoke(ctx, "/spire.api.server.bootstrap.v1.Boostrap/GetTrustAnchorARN", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BoostrapServer is the server API for Boostrap service.
// All implementations must embed UnimplementedBoostrapServer
// for forward compatibility
type BoostrapServer interface {
	// Get trust anchor ARN
	GetTrustAnchorARN(context.Context, *GetTrustAnchorARNRequest) (*GetTrustAnchorARNResponse, error)
	mustEmbedUnimplementedBoostrapServer()
}

// UnimplementedBoostrapServer must be embedded to have forward compatible implementations.
type UnimplementedBoostrapServer struct {
}

func (UnimplementedBoostrapServer) GetTrustAnchorARN(context.Context, *GetTrustAnchorARNRequest) (*GetTrustAnchorARNResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrustAnchorARN not implemented")
}
func (UnimplementedBoostrapServer) mustEmbedUnimplementedBoostrapServer() {}

// UnsafeBoostrapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BoostrapServer will
// result in compilation errors.
type UnsafeBoostrapServer interface {
	mustEmbedUnimplementedBoostrapServer()
}

func RegisterBoostrapServer(s grpc.ServiceRegistrar, srv BoostrapServer) {
	s.RegisterService(&_Boostrap_serviceDesc, srv)
}

func _Boostrap_GetTrustAnchorARN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrustAnchorARNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoostrapServer).GetTrustAnchorARN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spire.api.server.bootstrap.v1.Boostrap/GetTrustAnchorARN",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoostrapServer).GetTrustAnchorARN(ctx, req.(*GetTrustAnchorARNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Boostrap_serviceDesc = grpc.ServiceDesc{
	ServiceName: "spire.api.server.bootstrap.v1.Boostrap",
	HandlerType: (*BoostrapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTrustAnchorARN",
			Handler:    _Boostrap_GetTrustAnchorARN_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spire/api/server/bootstrap/v1/bootstrap.proto",
}
